[ 2025-01-14 13:32:09,137 ] 87 root - ERROR - An error occurred: Error occured in python script name [/Users/ishantsingh/data_science/Web Shield/push_data.py] line number [29] error message [no nameservers]
